services:
  api:
    # build: . - to create image using Dockerfile
    image: raypalmerrox/posts-fastapi
    container_name: api
    ports:
      - 80:8000
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: psgr
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

# run the following after docker compose up:
# docker compose run --rm api alembic upgrade head
# this will set up the tables on the database

# docker compose -f compose-prod.yml up -d - to start
# docker compose -f compose-prod.yml up -d - to stop
